app_name: "chat-with-ollama"
debug_mode: true
server:
  http_host: 0.0.0.0
  http_port: 8000
  grpc_host: 0.0.0.0
  grpc_port: 50051
ollama:
  host: http://ollama
  port: 11434
  model: llama3.2:latest
log:
  file: "chat.log"
